export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_INVALID_CREDENTIALS = "SET_INVALID_CREDENTIALS";
export const SET_INTERNAL_SERVER_ERROR = "SET_INTERNAL_SERVER_ERROR";
export const SET_CONNECTION_REFUSED_ERROR = "SET_CONNECTION_REFUSED_ERROR";
export const SET_INVALID_EMAIL = "SET_INVALID_EMAIL";
export const SET_VALID_EMAIL = "SET_VALID_EMAIL";
export const SET_INVALID_TOKEN = "SET_INVALID_TOKEN";
export const SET_VALID_PASSWORD = "SET_VALID_PASSWORD";
 
export const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";
 

export const FETCH_USER_ERROR = "FETCH_USER_ERROR";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"; 
 
 